ddr_gitki_search:
    path:   /search/
    defaults: { _controller: Dontdrinkandroot\GitkiBundle\Controller\SearchController:searchAction }

ddr_gitki_history:
    path:   /history
    defaults: { _controller: Dontdrinkandroot\GitkiBundle\Controller\RepositoryController:historyAction }

ddr_gitki_directory:
    path:   /browse{path}
    defaults: { _controller: Dontdrinkandroot\GitkiBundle\Controller\RepositoryController:directoryAction }
    requirements:
        path: .*/

ddr_gitki_file:
    path:   /browse{path}
    defaults: { _controller: Dontdrinkandroot\GitkiBundle\Controller\RepositoryController:fileAction }
    requirements:
        path: .+

ddr_gitki_meta_directories_json:
    path: /meta/directories.json
    defaults: { _controller: DdrGitkiBundle:Metadata:directoriesJson }

ddr_gitki_meta_files_json:
    path: /meta/files.json
    defaults: { _controller: DdrGitkiBundle:Metadata:filesJson }
