ddr_gitki_search:
    path:   /search/
    defaults: { _controller: DdrGitkiBundle:Search:search }

ddr_gitki_history:
    path:   /history
    defaults: { _controller: DdrGitkiBundle:Repository:history }

ddr_gitki_directory:
    path:   /browse{path}
    defaults: { _controller: DdrGitkiBundle:Repository:directory }
    requirements:
        path: .*/

ddr_gitki_file:
    path:   /browse{path}
    defaults: { _controller: DdrGitkiBundle:Repository:file }
    requirements:
        path: .+
