ddr_gitki_search:
    path:   /search/
    defaults: { _controller: DdrGitkiBaseBundle:Search:search }

ddr_gitki_history:
    path:   /history
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:history }

ddr_gitki_directory:
    path:   /browse{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:directory }
    requirements:
        path: .*/

ddr_gitki_file:
    path:   /browse{path}
    defaults: { _controller: DdrGitkiBaseBundle:Wiki:file }
    requirements:
        path: .+
