parameters:

services:

    ddr.gitki.repository.elasticsearch:
        class:  Dontdrinkandroot\Gitki\BaseBundle\Repository\NoopElasticsearchRepository
        tags:
            - { name: kernel.event_listener, event: ddr.gitki.file.changed, method: onFileChanged }
            - { name: kernel.event_listener, event: ddr.gitki.file.deleted, method: onFileDeleted }
            - { name: kernel.event_listener, event: ddr.gitki.file.moved, method: onFileMoved }

    ddr.gitki.twig.gitki_extension:
        class: Dontdrinkandroot\Gitki\BaseBundle\Twig\GitkiExtension
        tags:
            - { name: twig.extension }

    ddr.gitki.repository.git:
        class: Dontdrinkandroot\Gitki\BaseBundle\Repository\GitRepository
        arguments: [%ddr_gitki_base.repository_path%]

    ddr.gitki.service.lock:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\LockService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\EventDispatchingWikiService
        arguments:
            - @ddr.gitki.repository.git
            - @ddr.gitki.service.lock
            - @event_dispatcher
        calls:
            - [setWatcherRole, ['%ddr_gitki.role.watcher%']]
            - [setCommitterRole, ['%ddr_gitki.role.committer%']]
            - [setAdminRole, ['%ddr_gitki.role.admin%']]

    ddr.gitki.router.action_resolver:
        class: Dontdrinkandroot\Gitki\BaseBundle\Routing\ActionResolver
        calls:
            - [registerFileAction, ['DdrGitkiBaseBundle:File:serve']]
            - [registerFileAction, ['DdrGitkiBaseBundle:File:serve', 'raw']]
            - [registerFileAction, ['DdrGitkiBaseBundle:File:delete', 'delete']]
            - [registerFileAction, ['DdrGitkiBaseBundle:File:holdLock', 'holdlock']]
            - [registerFileAction, ['DdrGitkiBaseBundle:File:history', 'history']]
            - [registerFileAction, ['DdrGitkiBaseBundle:File:rename', 'rename']]
            - [registerFileAction, ['DdrGitkiBaseBundle:Text:view', '', 'txt']]
            - [registerFileAction, ['DdrGitkiBaseBundle:Text:edit', 'edit', 'txt']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:list']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:list', 'list']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:index', 'index']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:createSubdirectory', 'addfolder']] #TODO: deprecated
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:createSubdirectory', 'createsubdirectory']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:createFile', 'create']] #TODO: deprecated
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:createFile', 'createfile']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:delete', 'delete']]
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:uploadFile', 'upload']] #TODO: deprecated
            - [registerDirectoryAction, ['DdrGitkiBaseBundle:Directory:uploadFile', 'uploadfile']]

