parameters:

services:

    ddr.gitki.repository.elasticsearch:
        class:  Dontdrinkandroot\Gitki\BaseBundle\Repository\NoopElasticsearchRepository
        tags:
            - { name: kernel.event_listener, event: ddr.gitki.file.changed, method: onFileChanged }
            - { name: kernel.event_listener, event: ddr.gitki.file.deleted, method: onFileDeleted }
            - { name: kernel.event_listener, event: ddr.gitki.file.moved, method: onFileMoved }

    ddr.gitki.twig.gitki_extension:
        class: Dontdrinkandroot\Gitki\BaseBundle\Twig\GitkiExtension
        tags:
            - { name: twig.extension }

    ddr.gitki.repository.git:
        class: Dontdrinkandroot\Gitki\BaseBundle\Repository\GitRepository
        arguments: [%ddr_gitki_base.repository_path%]

    ddr.gitki.service.lock:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\LockService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Dontdrinkandroot\Gitki\BaseBundle\Service\EventDispatchingWikiService
        arguments:
            - @ddr.gitki.repository.git
            - @ddr.gitki.service.lock
            - @event_dispatcher

    # ROUTING

    ddr.gitki.router.route_provider:
        class: Dontdrinkandroot\Gitki\BaseBundle\Routing\RouteProvider
        calls:
            - [registerFileAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\FileController::serveAction']]
            - [registerFileAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\FileController::serveAction', 'raw']]
            - [registerFileAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\FileController::deleteAction', 'delete']]
            - [registerFileAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\FileController::holdLockAction', 'holdlock']]
            - [registerFileAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\FileController::historyAction', 'history']]
            - [registerFileAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\FileController::renameAction', 'rename']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::listAction']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::indexAction', 'index']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::createSubdirectoryAction', 'addfolder']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::createSubdirectoryAction', 'createsubdirectory']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::createFileAction', 'create']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::createFileAction', 'createfile']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::deleteAction', 'delete']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::uploadFileAction', 'upload']]
            - [registerDirectoryAction, ['Dontdrinkandroot\Gitki\BaseBundle\Controller\DirectoryController::uploadFileAction', 'uploadfile']]

    ddr.giki.router.request_matcher:
        class: Dontdrinkandroot\Gitki\BaseBundle\Routing\WikiRequestMatcher
        arguments:
            - @ddr.gitki.router.route_provider

    ddr.gitki.router.listener:
        class: Dontdrinkandroot\Gitki\BaseBundle\Routing\WikiRouterListener
        arguments:
            - @ddr.giki.router.request_matcher
            - @router.request_context
            - @logger
            - @request_stack
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 33 }
