parameters:

services:

    Dontdrinkandroot\GitkiBundle\Analyzer\TextAnalyzer:
        tags:
            -  { name: ddr.gitki.analyzer }

    Dontdrinkandroot\GitkiBundle\Analyzer\MarkdownAnalyzer:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Markdown\MarkdownServiceInterface'
        tags:
            -  { name: ddr.gitki.analyzer }

    Dontdrinkandroot\GitkiBundle\Repository\NoopElasticsearchRepository: ~

    Dontdrinkandroot\GitkiBundle\Repository\ElasticsearchRepositoryInterface: '@Dontdrinkandroot\GitkiBundle\Repository\NoopElasticsearchRepository'

    Dontdrinkandroot\GitkiBundle\Twig\GitkiExtension:
        arguments:
            - '@security.authorization_checker'
            - '@Dontdrinkandroot\GitkiBundle\Service\Role\RoleService'
            - '@Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistry'
        tags:
            - { name: twig.extension }

    Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistry:
        calls:
            - [registerFileAction, ['DdrGitkiBundle:File:serve']]
            - [registerFileAction, ['DdrGitkiBundle:File:serve', 'raw']]
            - [registerFileAction, ['DdrGitkiBundle:File:remove', 'remove']]
            - [registerFileAction, ['DdrGitkiBundle:File:holdLock', 'holdlock']]
            - [registerFileAction, ['DdrGitkiBundle:File:history', 'history']]
            - [registerFileAction, ['DdrGitkiBundle:File:move', 'move']]
            - [registerFileAction, ['DdrGitkiBundle:File:cancel', 'cancel']]
            - [registerFileAction, ['DdrGitkiBundle:Markdown:preview','preview','md']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:index']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:list', 'list']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:index', 'index']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:createSubdirectory','subdirectory.create']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:createFile', 'file.create']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:remove', 'remove']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:uploadFile', 'file.upload']]
            - [registerExtension, ['txt', 'Text', 'DdrGitkiBundle:Text:view','DdrGitkiBundle:Text:edit']]
            - [registerExtension, ['md', 'Markdown', 'DdrGitkiBundle:Markdown:view','DdrGitkiBundle:Markdown:edit']]

    Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistryInterface: '@Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistry'

    Dontdrinkandroot\GitkiBundle\Service\FileSystem\FileSystemService:
        arguments:
            - '%ddr_gitki.repository_path%'

    Dontdrinkandroot\GitkiBundle\Service\Git\GitService:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\FileSystem\FileSystemService'

    Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\NoopElasticsearchService:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Git\GitService'
            - '@Dontdrinkandroot\GitkiBundle\Repository\ElasticsearchRepositoryInterface'
        tags:
            - { name: kernel.event_listener, event: ddr.gitki.file.changed, method: onFileChanged }
            - { name: kernel.event_listener, event: ddr.gitki.file.removed, method: onFileRemoved }
            - { name: kernel.event_listener, event: ddr.gitki.file.moved, method: onFileMoved }

    Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\ElasticsearchServiceInterface: '@Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\NoopElasticsearchService'

    Dontdrinkandroot\GitkiBundle\Service\Lock\LockService:
        arguments: ['@Dontdrinkandroot\GitkiBundle\Service\FileSystem\FileSystemService']

    Dontdrinkandroot\GitkiBundle\Service\Role\RoleService:
        calls:
            - [setWatcherRole, ['%ddr_gitki.role.watcher%']]
            - [setCommitterRole, ['%ddr_gitki.role.committer%']]
            - [setAdminRole, ['%ddr_gitki.role.admin%']]

    Dontdrinkandroot\GitkiBundle\Service\Directory\ElasticsearchAwareDirectoryService:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\FileSystem\FileSystemService'
            - '@Dontdrinkandroot\GitkiBundle\Repository\ElasticsearchRepositoryInterface'
        calls:
            - [setIndexFiles, ['%ddr_gitki.index_files%']]

    Dontdrinkandroot\GitkiBundle\Service\Directory\DirectoryServiceInterface: '@Dontdrinkandroot\GitkiBundle\Service\Directory\ElasticsearchAwareDirectoryService'

    Dontdrinkandroot\GitkiBundle\Service\Wiki\EventDispatchingWikiService:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Git\GitService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Lock\LockService'
            - '@event_dispatcher'

    Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService: '@Dontdrinkandroot\GitkiBundle\Service\Wiki\EventDispatchingWikiService'

    Dontdrinkandroot\GitkiBundle\Service\Markdown\FileSystemAwareMarkdownService:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\FileSystem\FileSystemService'
            - '%ddr_gitki_markdown.allow_html%'

    Dontdrinkandroot\GitkiBundle\Service\Markdown\MarkdownServiceInterface: '@Dontdrinkandroot\GitkiBundle\Service\Markdown\FileSystemAwareMarkdownService'

    Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService:
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
            - '@Dontdrinkandroot\GitkiBundle\Service\Role\RoleService'

    #
    # Commands
    #

    Dontdrinkandroot\GitkiBundle\Command\ReindexCommand:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\ElasticsearchServiceInterface'
        tags:
            - { name: console.command }

    Dontdrinkandroot\GitkiBundle\Command\SearchCommand:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\ElasticsearchServiceInterface'
        tags:
            - { name: console.command }

    #
    # Controllers
    #

    Dontdrinkandroot\GitkiBundle\Controller\RepositoryController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistryInterface'
            - '@Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Dontdrinkandroot\GitkiBundle\Controller\MarkdownController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Directory\DirectoryServiceInterface'
            - '@Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistryInterface'
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Markdown\MarkdownServiceInterface'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Dontdrinkandroot\GitkiBundle\Controller\FileController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Directory\DirectoryServiceInterface'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Dontdrinkandroot\GitkiBundle\Controller\DirectoryController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Directory\DirectoryServiceInterface'
            - '@Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistryInterface'
            - '@Dontdrinkandroot\GitkiBundle\Service\FileSystem\FileSystemService'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Dontdrinkandroot\GitkiBundle\Controller\TextController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Wiki\WikiService'
            - '@Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistryInterface'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Dontdrinkandroot\GitkiBundle\Controller\SearchController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\ElasticsearchServiceInterface'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]

    Dontdrinkandroot\GitkiBundle\Controller\MetadataController:
        arguments:
            - '@Dontdrinkandroot\GitkiBundle\Service\Security\SecurityService'
            - '@Dontdrinkandroot\GitkiBundle\Service\Directory\DirectoryServiceInterface'
        public: true
        calls:
            - [ setContainer, [ '@service_container' ] ]