parameters:

services:

    # ANALYZERS

    ddr.gitki.analyzer.text:
        class: Dontdrinkandroot\GitkiBundle\Analyzer\TextAnalyzer
        tags:
            -  { name: ddr.gitki.analyzer }

    ddr.gitki.analyzer.markdown:
        class: Dontdrinkandroot\GitkiBundle\Analyzer\MarkdownAnalyzer
        arguments:
            - '@ddr.gitki.service.markdown'
        tags:
            -  { name: ddr.gitki.analyzer }

    ddr.gitki.repository.elasticsearch:
        class:  Dontdrinkandroot\GitkiBundle\Repository\NoopElasticsearchRepository

    ddr.gitki.twig.gitki_extension:
        class: Dontdrinkandroot\GitkiBundle\Twig\GitkiExtension
        arguments:
            - @security.context
            - @ddr.gitki.service.wiki
            - @ddr.gitki.registry.extension
        tags:
            - { name: twig.extension }

    ddr.gitki.repository.git:
        class: Dontdrinkandroot\GitkiBundle\Repository\GitRepository
        arguments: [%ddr_gitki.repository_path%]

    ddr.gitki.registry.extension:
        class: Dontdrinkandroot\GitkiBundle\Service\ExtensionRegistry\ExtensionRegistry
        calls:
            - [registerFileAction, ['DdrGitkiBundle:File:serve']]
            - [registerFileAction, ['DdrGitkiBundle:File:serve', 'raw']]
            - [registerFileAction, ['DdrGitkiBundle:File:delete', 'delete']]
            - [registerFileAction, ['DdrGitkiBundle:File:holdLock', 'holdlock']]
            - [registerFileAction, ['DdrGitkiBundle:File:history', 'history']]
            - [registerFileAction, ['DdrGitkiBundle:File:rename', 'rename']]
            - [registerFileAction, ['DdrGitkiBundle::Markdown:preview','preview','md']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:list']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:list', 'list']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:index', 'index']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:createSubdirectory', 'createsubdirectory']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:createFile', 'createfile']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:delete', 'delete']]
            - [registerDirectoryAction, ['DdrGitkiBundle:Directory:uploadFile', 'uploadfile']]
            - [registerExtension, ['txt', 'Text', 'DdrGitkiBundle:Text:view','DdrGitkiBundle:Text:edit']]
            - [registerExtension, ['md', 'Markdown', 'DdrGitkiBundle:Markdown:view','DdrGitkiBundle:Markdown:edit']]

    ddr.gitki.service.elasticsearch:
        class: Dontdrinkandroot\GitkiBundle\Service\Elasticsearch\NoopElasticsearchService
        arguments:
            - @ddr.gitki.repository.git
            - @ddr.gitki.repository.elasticsearch
        tags:
            - { name: kernel.event_listener, event: ddr.gitki.file.changed, method: onFileChanged }
            - { name: kernel.event_listener, event: ddr.gitki.file.deleted, method: onFileDeleted }
            - { name: kernel.event_listener, event: ddr.gitki.file.moved, method: onFileMoved }

    ddr.gitki.service.lock:
        class: Dontdrinkandroot\GitkiBundle\Service\LockService
        arguments: [@ddr.gitki.repository.git]

    ddr.gitki.service.wiki:
        class: Dontdrinkandroot\GitkiBundle\Service\Wiki\EventDispatchingWikiService
        arguments:
            - @ddr.gitki.repository.git
            - @ddr.gitki.service.lock
            - @event_dispatcher
        calls:
            - [setWatcherRole, ['%ddr_gitki.role.watcher%']]
            - [setCommitterRole, ['%ddr_gitki.role.committer%']]
            - [setAdminRole, ['%ddr_gitki.role.admin%']]

    ddr.gitki.service.markdown:
        class: Dontdrinkandroot\GitkiBundle\Service\Markdown\RepositoryAwareMarkdownService
        arguments:
            - @ddr.gitki.repository.git
            - '%ddr_gitki_markdown.allow_html%'