filter:
    excluded_paths: [Tests/*]
tools:
    php_code_coverage: false
    external_code_coverage:
        runs: 2
        timeout: 1200
checks:
    php:
        code_rating: true
        duplication: true
