language: php

php:
    - 5.5
    - 5.6

before_script:
    - composer install --dev
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"

script:
    - vendor/bin/phpunit