language: php

matrix:
    include:
        -
            php: 7.1
            env: dependencies=lowest
        -
            php: 7.1
            env: dependencies=highest

services:
  - elasticsearch

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.3.1.deb && sudo service elasticsearch restart

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [ -z "$dependencies" ]; then composer install; fi;
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
    - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"
    - curl -XGET 'localhost:9200'

script:
    - SYMFONY_DEPRECATIONS_HELPER="weak" vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
