language: php

sudo: false

php:
    - 5.5
    - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_script:
    - composer self-update -q
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - composer install
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
