language: php

matrix:
    include:
        -   php: 7.2
            env: dependencies=lowest
        -   php: 7.2
            env: dependencies=highest
        -   php: 7.3
            env: dependencies=lowest
        -   php: 7.3
            env: dependencies=highest
        -   php: 7.4
            env: dependencies=lowest
        -   php: 7.4
            env: dependencies=highest

services:
    - elasticsearch

cache:
    directories:
        - $HOME/.composer/cache

addons:
    sonarcloud:
        organization: "dontdrinkandroot"
        token: $SONAR_TOKEN

before_install:
    - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.8.1-amd64.deb && sudo dpkg -i --force-confnew elasticsearch-7.8.1-amd64.deb && sudo service elasticsearch restart
    - sleep 10
    - sudo tail -n 500 /var/log/elasticsearch/elasticsearch.log
    - curl -XGET http://localhost:9200
    #- until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

before_script:
    - phpenv config-rm xdebug.ini
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [ -z "$dependencies" ]; then composer install; fi;
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest -n; fi;
    - if [ "$dependencies" = "highest" ] && ["$TRAVIS_PHP_VERSION" = "7.4" ]; then pecl install pcov; fi;
    - if [ "$dependencies" = "highest" ]; then composer update -n; fi;
    - git config --global user.email "gitki@dontdrinkandroot.net"
    - git config --global user.name "GitKi"

script:
    - SYMFONY_DEPRECATIONS_HELPER="weak" vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
    - if [ "$dependencies" = "highest" ] && ["$TRAVIS_PHP_VERSION" = "7.4" ]; then sonar-scanner; fi;
